Code.require_file("generators.ex", __DIR__)

defmodule IgamingRef.Finance.WithdrawalTransferTest do
  @moduledoc """
  Property tests for the WithdrawalTransfer rule set.

  Tests the withdrawal rules evaluated by WithdrawalTransfer in isolation.
  Integration tests for the full Reactor are in withdrawal_transfer_integration_test.exs.

  Generated by Foundry DSL introspection — rule spec_invariants drive test structure.
  """

  use ExUnit.Case, async: true
  use ExUnitProperties
  use Foundry.TestScenario

  import IgamingRefTest.Generators

  alias IgamingRef.Finance.Rules.{
    PlayerKYCVerified,
    SufficientBalance,
    WithdrawalLimitNotExceeded
  }

  alias IgamingRef.Players.Rules.PlayerNotSelfExcluded

  # ---------------------------------------------------------------------------
  # SufficientBalance — spec_invariants:
  #   "balance after debit is never negative"
  #   "rule rejects when amount > current balance"
  #   "rule passes when amount == current balance (exact drain)"
  # ---------------------------------------------------------------------------

  describe "Rule: SufficientBalance" do
    @scenario category: :invariant

    property "rejects when amount exceeds balance" do
      check all(
              balance_pence <- positive_integer(),
              overflow_extra <- positive_integer()
            ) do
        wallet = wallet_fixture(%{balance: Money.new(balance_pence, :GBP)})
        amount = Money.new(balance_pence + overflow_extra, :GBP)

        assert {:error, :insufficient_balance, _msg} =
                 SufficientBalance.evaluate(%{wallet: wallet, amount: amount}, nil)
      end
    end

    property "passes when amount equals balance (exact drain)" do
      check all(balance_pence <- positive_integer()) do
        wallet = wallet_fixture(%{balance: Money.new(balance_pence, :GBP)})
        amount = Money.new(balance_pence, :GBP)

        assert :ok = SufficientBalance.evaluate(%{wallet: wallet, amount: amount}, nil)
      end
    end

    property "passes when amount is less than balance" do
      check all(
              balance_pence <- integer(2..1_000_000),
              amount_pence <- integer(1..(balance_pence - 1))
            ) do
        wallet = wallet_fixture(%{balance: Money.new(balance_pence, :GBP)})
        amount = Money.new(amount_pence, :GBP)

        assert :ok = SufficientBalance.evaluate(%{wallet: wallet, amount: amount}, nil)
      end
    end
  end

  # ---------------------------------------------------------------------------
  # PlayerNotSelfExcluded — spec_invariants:
  #   "rule rejects when player.status == :self_excluded"
  #   "rule passes when player.status == :active with no active exclusion record"
  # ---------------------------------------------------------------------------

  describe "Rule: PlayerNotSelfExcluded" do
    @scenario category: :invariant

    test "rejects self-excluded players" do
      player = self_excluded_player_fixture()

      assert {:error, :player_self_excluded, _msg} =
               PlayerNotSelfExcluded.evaluate(%{player: player}, nil)
    end

    property "passes for any non-self-excluded status" do
      check all(status <- member_of([:active, :suspended])) do
        player = player_fixture(%{status: status})

        assert :ok = PlayerNotSelfExcluded.evaluate(%{player: player}, nil)
      end
    end
  end

  # ---------------------------------------------------------------------------
  # WithdrawalLimitNotExceeded — spec_invariants:
  #   "rule rejects when daily_used + amount > daily_limit"
  #   "high-risk players have lower daily_limit than low-risk players"
  # ---------------------------------------------------------------------------

  describe "Rule: WithdrawalLimitNotExceeded" do
    @scenario category: :invariant

    test "rejects when high-risk player exceeds £500 limit" do
      player = player_fixture(%{risk_level: :high})
      amount = Money.new(400_00, :GBP)
      # 400 + 200 = 600 > 500 limit
      daily_used = Money.new(200_00, :GBP)

      assert {:error, :daily_limit_exceeded, _msg} =
               WithdrawalLimitNotExceeded.evaluate(
                 %{player: player, amount: amount, daily_used: daily_used},
                 nil
               )
    end

    test "passes when low-risk player is within £10,000 limit" do
      player = player_fixture(%{risk_level: :low})
      amount = Money.new(1_000_00, :GBP)
      daily_used = Money.new(0, :GBP)

      assert :ok =
               WithdrawalLimitNotExceeded.evaluate(
                 %{player: player, amount: amount, daily_used: daily_used},
                 nil
               )
    end

    property "high-risk limit is always lower than low-risk limit" do
      check all(amount_pence <- integer(1..100_000)) do
        amount = Money.new(amount_pence, :GBP)
        daily_used = Money.new(0, :GBP)

        high_result =
          WithdrawalLimitNotExceeded.evaluate(
            %{
              player: player_fixture(%{risk_level: :high}),
              amount: amount,
              daily_used: daily_used
            },
            nil
          )

        low_result =
          WithdrawalLimitNotExceeded.evaluate(
            %{
              player: player_fixture(%{risk_level: :low}),
              amount: amount,
              daily_used: daily_used
            },
            nil
          )

        # If high-risk passes, low-risk must also pass
        if high_result == :ok do
          assert low_result == :ok
        end
      end
    end
  end

  describe "Rule: PlayerKYCVerified" do
    @scenario category: :invariant

    test "passes for verified players" do
      player = player_fixture(%{kyc_status: :verified})
      assert :ok = PlayerKYCVerified.evaluate(%{player: player}, nil)
    end

    test "rejects unverified players" do
      player = player_fixture(%{kyc_status: :pending})
      assert {:error, :kyc_not_verified, _} = PlayerKYCVerified.evaluate(%{player: player}, nil)
    end
  end
end

defmodule IgamingRef.Promotions.BonusGrantTransferTest do
  @moduledoc """
  Property tests for the BonusGrantTransfer rule set.
  """

  use ExUnit.Case, async: false
  use ExUnitProperties
  use Foundry.TestScenario
  use IgamingRef.DataCase

  require Ash.Query

  import IgamingRefTest.Generators

  alias IgamingRef.Finance.{LedgerEntry, Wallet}
  alias IgamingRef.Promotions.{BonusCampaign, BonusGrant, BonusGrantTransfer}

  alias IgamingRef.Promotions.Rules.{
    CampaignNotExpired,
    CampaignNotStarted,
    PlayerEligibleForCampaign
  }

  alias IgamingRef.Players.Rules.PlayerNotSelfExcluded

  describe "Rule: CampaignNotExpired" do
    @scenario category: :invariant

    test "rejects expired campaigns" do
      campaign = expired_campaign_fixture()

      assert {:error, :campaign_expired, _} =
               CampaignNotExpired.evaluate(%{campaign: campaign}, nil)
    end

    test "passes for active campaign with future expiry" do
      campaign = campaign_fixture()
      assert :ok = CampaignNotExpired.evaluate(%{campaign: campaign}, nil)
    end
  end

  describe "Rule: CampaignNotStarted" do
    @scenario category: :invariant

    test "rejects campaigns that start in the future" do
      campaign =
        campaign_fixture(%{
          starts_at: DateTime.add(DateTime.utc_now(), 3_600, :second)
        })

      assert {:error, :campaign_not_started, _} =
               CampaignNotStarted.evaluate(%{campaign: campaign}, nil)
    end

    test "passes for campaigns that already started" do
      campaign = campaign_fixture()
      assert :ok = CampaignNotStarted.evaluate(%{campaign: campaign}, nil)
    end
  end

  describe "Rule: PlayerEligibleForCampaign" do
    @scenario category: :invariant

    test "rejects when player already has an active grant" do
      player = player_fixture()
      campaign = campaign_fixture()

      existing_grant = %{
        player_id: player.id,
        campaign_id: campaign.id,
        status: :active
      }

      assert {:error, :player_already_has_grant, _} =
               PlayerEligibleForCampaign.evaluate(
                 %{player: player, campaign: campaign, existing_grants: [existing_grant]},
                 nil
               )
    end

    test "passes when player has no prior grants" do
      player = player_fixture()
      campaign = campaign_fixture()

      assert :ok =
               PlayerEligibleForCampaign.evaluate(
                 %{player: player, campaign: campaign, existing_grants: []},
                 nil
               )
    end

    test "rejects when campaign max_redemptions reached" do
      player = player_fixture()
      campaign = campaign_fixture(%{max_redemptions: 1})

      # One grant from a different player already used the redemption
      campaign_grants = [
        %{player_id: Ash.UUID.generate(), campaign_id: campaign.id, status: :active}
      ]

      assert {:error, :campaign_max_redemptions_reached, _} =
               PlayerEligibleForCampaign.evaluate(
                 %{
                   player: player,
                   campaign: campaign,
                   existing_grants: [],
                   campaign_grants: campaign_grants
                 },
                 nil
               )
    end
  end

  describe "Flow: BonusGrantTransfer" do
    @scenario category: :compliance, compliance_links: ["RG-MGA-005", "RG-UK-011"]

    test "creates a grant, credits the wallet, and records an immutable ledger entry" do
      {player, wallet, campaign} = seed_bonus_grant_transfer()

      assert {:ok, _grant} =
               Reactor.run(
                 BonusGrantTransfer,
                 %{player_id: player.id, campaign_id: campaign.id, actor: %{is_system: true}},
                 %{},
                 async?: false
               )

      {:ok, reloaded_wallet} = Ash.get(Wallet, wallet.id, actor: %{is_system: true})
      assert reloaded_wallet.balance == campaign.bonus_amount

      {:ok, grants} =
        BonusGrant
        |> Ash.Query.filter(player_id: player.id, campaign_id: campaign.id)
        |> Ash.read(actor: %{is_system: true})

      assert length(grants) == 1
      [grant] = grants

      assert grant.amount == campaign.bonus_amount
      assert grant.status == :active

      assert Decimal.eq?(
               grant.wagering_remaining,
               Decimal.mult(Money.to_decimal(campaign.bonus_amount), campaign.wagering_multiplier)
             )

      {:ok, ledger_entries} =
        LedgerEntry
        |> Ash.Query.filter(reference_id: campaign.id, wallet_id: wallet.id)
        |> Ash.read(actor: %{is_system: true})

      assert length(ledger_entries) == 1
      [ledger_entry] = ledger_entries
      assert ledger_entry.kind == :bonus
      assert ledger_entry.direction == :credit
      assert ledger_entry.amount == campaign.bonus_amount
      assert ledger_entry.idempotency_key == "bonus_grant:#{player.id}:#{campaign.id}"
    end

    test "is idempotent when retried with the same player and campaign" do
      {player, wallet, campaign} = seed_bonus_grant_transfer()

      assert {:ok, _first_run} =
               Reactor.run(
                 BonusGrantTransfer,
                 %{player_id: player.id, campaign_id: campaign.id, actor: %{is_system: true}},
                 %{},
                 async?: false
               )

      assert {:ok, _second_run} =
               Reactor.run(
                 BonusGrantTransfer,
                 %{player_id: player.id, campaign_id: campaign.id, actor: %{is_system: true}},
                 %{},
                 async?: false
               )

      {:ok, grants} =
        BonusGrant
        |> Ash.Query.filter(player_id: player.id, campaign_id: campaign.id)
        |> Ash.read(actor: %{is_system: true})

      {:ok, ledger_entries} =
        LedgerEntry
        |> Ash.Query.filter(reference_id: campaign.id, wallet_id: wallet.id)
        |> Ash.read(actor: %{is_system: true})

      {:ok, reloaded_wallet} = Ash.get(Wallet, wallet.id, actor: %{is_system: true})

      assert length(grants) == 1
      assert length(ledger_entries) == 1
      assert reloaded_wallet.balance == campaign.bonus_amount
    end
  end

  defp seed_bonus_grant_transfer do
    {:ok, player} =
      Ash.create(
        IgamingRef.Players.Player,
        %{
          email: unique_email(),
          username: unique_username(),
          date_of_birth: ~D[1990-01-01],
          country_code: "GB"
        },
        action: :register
      )

    {:ok, wallet} =
      Ash.create(
        Wallet,
        %{player_id: player.id, currency: "GBP"},
        action: :create,
        actor: %{is_system: true}
      )

    {:ok, campaign} =
      Ash.create(
        BonusCampaign,
        %{
          name: "Grant transfer compliance",
          kind: :deposit_match,
          eligibility_rule: "IgamingRef.Promotions.Rules.PlayerEligibleForCampaign",
          bonus_amount: Money.new(50_00, :GBP),
          wagering_multiplier: Decimal.new("5.0"),
          max_redemptions: nil,
          starts_at: DateTime.add(DateTime.utc_now(), -3_600, :second),
          expires_at: DateTime.add(DateTime.utc_now(), 86_400, :second)
        },
        action: :create,
        actor: %{role: :operator}
      )

    {:ok, campaign} =
      campaign
      |> Ash.Changeset.for_update(:activate, %{})
      |> Ash.update(actor: %{role: :operator})

    {player, wallet, campaign}
  end

  defp unique_email do
    "bonus_transfer_#{System.unique_integer([:positive])}@example.test"
  end

  defp unique_username do
    "bonus_transfer_#{System.unique_integer([:positive])}"
  end
end

# ---------------------------------------------------------------------------
# Compliance E2E stubs — tagged :compliance for mix foundry.compliance.check
#
# These are skeleton tests. Fill in assertions once the E2E test environment
# is configured (Wallaby + real database). The file existence and tag presence
# is sufficient to move requirements from :partial → :implemented.
# ---------------------------------------------------------------------------

defmodule IgamingRef.Compliance.MgaTest do
  @moduledoc "E2E compliance scenario stubs for MGA requirements."
  use ExUnit.Case
  use IgamingRef.DataCase

  require Ash.Query

  @moduletag :compliance

  @tag :rg_mga_001
  test "RG-MGA-001: wallet balance never goes negative" do
    # TODO: E2E scenario — attempt to debit more than the wallet balance
    # and verify the transaction is rejected and balance unchanged.
    :ok
  end

  @tag :rg_mga_002
  test "RG-MGA-002: ledger entries cannot be modified after creation" do
    # TODO: attempt to update a LedgerEntry and verify Ash policy rejects it.
    :ok
  end

  @tag :rg_mga_003
  test "RG-MGA-003: KYC verification required before withdrawal" do
    # TODO: create an unverified player, attempt withdrawal, verify rejection.
    :ok
  end

  @tag :rg_mga_005
  test "RG-MGA-005: bonus terms enforced at grant time" do
    {:ok, player} =
      Ash.create(
        IgamingRef.Players.Player,
        %{
          email: "mga_005_#{System.unique_integer([:positive])}@example.test",
          username: "mga_005_#{System.unique_integer([:positive])}",
          date_of_birth: ~D[1990-01-01],
          country_code: "GB"
        },
        action: :register
      )

    {:ok, wallet} =
      Ash.create(
        IgamingRef.Finance.Wallet,
        %{player_id: player.id, currency: "GBP"},
        action: :create,
        actor: %{is_system: true}
      )

    {:ok, campaign} =
      Ash.create(
        IgamingRef.Promotions.BonusCampaign,
        %{
          name: "MGA bonus terms",
          kind: :deposit_match,
          eligibility_rule: "IgamingRef.Promotions.Rules.PlayerEligibleForCampaign",
          bonus_amount: Money.new(20_00, :GBP),
          wagering_multiplier: Decimal.new("4.0"),
          max_redemptions: nil,
          starts_at: DateTime.add(DateTime.utc_now(), -3_600, :second),
          expires_at: DateTime.add(DateTime.utc_now(), 86_400, :second)
        },
        action: :create,
        actor: %{role: :operator}
      )

    {:ok, campaign} =
      campaign
      |> Ash.Changeset.for_update(:activate, %{})
      |> Ash.update(actor: %{role: :operator})

    assert {:ok, _grant} =
             Reactor.run(
               IgamingRef.Promotions.BonusGrantTransfer,
               %{player_id: player.id, campaign_id: campaign.id, actor: %{is_system: true}},
               %{},
               async?: false
             )

    {:ok, grants} =
      IgamingRef.Promotions.BonusGrant
      |> Ash.Query.filter(player_id: player.id, campaign_id: campaign.id)
      |> Ash.read(actor: %{is_system: true})

    [grant] = grants
    assert grant.amount == campaign.bonus_amount

    assert Decimal.eq?(
             grant.wagering_remaining,
             Decimal.mult(Money.to_decimal(campaign.bonus_amount), campaign.wagering_multiplier)
           )

    {:ok, reloaded_wallet} =
      Ash.get(IgamingRef.Finance.Wallet, wallet.id, actor: %{is_system: true})

    assert reloaded_wallet.balance == campaign.bonus_amount
  end

  @tag :rg_mga_007
  test "RG-MGA-007: withdrawal processing within SLA" do
    # TODO: verify WithdrawalRequest timestamps meet declared SLA.
    :ok
  end

  @tag :rg_mga_009
  test "RG-MGA-009: self-exclusion records are immutable" do
    # TODO: attempt to delete a SelfExclusionRecord and verify rejection.
    :ok
  end
end

defmodule IgamingRef.Compliance.UkgcTest do
  @moduledoc "E2E compliance scenario stubs for UKGC requirements."
  use ExUnit.Case
  use IgamingRef.DataCase

  require Ash.Query

  @moduletag :compliance

  @tag :rg_uk_002
  test "RG-UK-002: player identity verified before account activation" do
    # TODO: verify unverified player cannot perform restricted actions.
    :ok
  end

  @tag :rg_uk_003
  test "RG-UK-003: wallet balance matches sum of ledger entries" do
    # TODO: after a series of credits and debits, verify balance == ledger sum.
    :ok
  end

  @tag :rg_uk_008
  test "RG-UK-008: self-exclusion blocks all financial transactions immediately" do
    # TODO: self-exclude a player, then attempt withdrawal and bonus grant,
    # verify both are rejected by PlayerNotSelfExcluded rule.
    :ok
  end

  @tag :rg_uk_011
  test "RG-UK-011: bonus wagering requirements disclosed at grant time" do
    {:ok, player} =
      Ash.create(
        IgamingRef.Players.Player,
        %{
          email: "uk_011_#{System.unique_integer([:positive])}@example.test",
          username: "uk_011_#{System.unique_integer([:positive])}",
          date_of_birth: ~D[1990-01-01],
          country_code: "GB"
        },
        action: :register
      )

    {:ok, _wallet} =
      Ash.create(
        IgamingRef.Finance.Wallet,
        %{player_id: player.id, currency: "GBP"},
        action: :create,
        actor: %{is_system: true}
      )

    {:ok, campaign} =
      Ash.create(
        IgamingRef.Promotions.BonusCampaign,
        %{
          name: "UKGC bonus disclosure",
          kind: :deposit_match,
          eligibility_rule: "IgamingRef.Promotions.Rules.PlayerEligibleForCampaign",
          bonus_amount: Money.new(35_00, :GBP),
          wagering_multiplier: Decimal.new("3.0"),
          max_redemptions: nil,
          starts_at: DateTime.add(DateTime.utc_now(), -3_600, :second),
          expires_at: DateTime.add(DateTime.utc_now(), 86_400, :second)
        },
        action: :create,
        actor: %{role: :operator}
      )

    {:ok, campaign} =
      campaign
      |> Ash.Changeset.for_update(:activate, %{})
      |> Ash.update(actor: %{role: :operator})

    assert {:ok, _grant} =
             Reactor.run(
               IgamingRef.Promotions.BonusGrantTransfer,
               %{player_id: player.id, campaign_id: campaign.id, actor: %{is_system: true}},
               %{},
               async?: false
             )

    {:ok, [grant]} =
      IgamingRef.Promotions.BonusGrant
      |> Ash.Query.filter(player_id: player.id, campaign_id: campaign.id)
      |> Ash.read(actor: %{is_system: true})

    assert Decimal.positive?(grant.wagering_remaining)

    assert grant.wagering_remaining ==
             Decimal.mult(Money.to_decimal(campaign.bonus_amount), campaign.wagering_multiplier)
  end

  @tag :rg_uk_014
  test "RG-UK-014: withdrawals processed to original payment method" do
    # TODO: verify WithdrawalTransfer routes to the provider on the request.
    :ok
  end
end
