defmodule IgamingRef.Repo.Migrations.InitIgamingRefSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:withdrawal_webhook_events, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:provider, :text, null: false)
      add(:provider_reference, :text, null: false)
      add(:event_type, :text, null: false)
      add(:status, :text, null: false)
      add(:payload, :map, null: false, default: %{})

      add(:received_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(
      unique_index(:withdrawal_webhook_events, [:provider, :provider_reference, :event_type],
        name: "withdrawal_webhook_events_unique_provider_reference_event_index"
      )
    )

    create table(:withdrawal_requests, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:player_id, :uuid, null: false)
      add(:wallet_id, :uuid, null: false)
      add(:amount, :money_with_currency, null: false)
      add(:status, :text, null: false, default: "pending")
      add(:provider, :text)
      add(:provider_reference, :text)
      add(:rejection_reason, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)
      add(:state, :text, null: false, default: "pending")
    end

    create table(:wallets, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:player_id, :uuid, null: false)
      add(:currency, :text, null: false)
      add(:balance, :money_with_currency, null: false, default: fragment("('GBP', 0)"))
      add(:status, :text, null: false, default: "active")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)
      add(:state, :text, null: false, default: "active")
    end

    create table(:users_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_source_id, :uuid, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:users, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:users_versions) do
      modify(
        :version_source_id,
        references(:users,
          column: :id,
          name: "users_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:users) do
      add(:email, :citext, null: false)
      add(:hashed_password, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)
    end

    create(unique_index(:users, [:email], name: "users_unique_email_index"))

    create table(:transfers, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:from_wallet_id, :uuid)
      add(:to_wallet_id, :uuid)
      add(:amount, :money_with_currency, null: false)
      add(:status, :text, null: false, default: "pending")
      add(:reason, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)
    end

    create table(:tokens_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_source_id, :text, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:tokens, primary_key: false) do
      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:extra_data, :map)
      add(:purpose, :text, null: false)
      add(:expires_at, :utc_datetime, null: false)
      add(:subject, :text, null: false)
      add(:jti, :text, null: false, primary_key: true)
    end

    alter table(:tokens_versions) do
      modify(
        :version_source_id,
        references(:tokens,
          column: :jti,
          name: "tokens_versions_version_source_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    alter table(:tokens) do
      add(:archived_at, :utc_datetime_usec)
    end

    create table(:self_exclusion_records, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:player_id, :uuid, null: false)
      add(:excluded_at, :utc_datetime, null: false)
      add(:exclusion_type, :text, null: false)
      add(:duration_days, :bigint)
      add(:reinstated_at, :utc_datetime)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)
    end

    create table(:provider_configs, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:provider_name, :text, null: false)
      add(:api_endpoint, :text, null: false)
      add(:api_key, :text, null: false)
      add(:status, :text, null: false, default: "active")
      add(:rtp_certified, :boolean, null: false, default: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)
    end

    create table(:players, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:withdrawal_requests) do
      modify(
        :player_id,
        references(:players,
          column: :id,
          name: "withdrawal_requests_player_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :wallet_id,
        references(:wallets,
          column: :id,
          name: "withdrawal_requests_wallet_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:wallets) do
      modify(
        :player_id,
        references(:players,
          column: :id,
          name: "wallets_player_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:self_exclusion_records) do
      modify(
        :player_id,
        references(:players,
          column: :id,
          name: "self_exclusion_records_player_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:players) do
      add(:email, :citext, null: false)
      add(:username, :text, null: false)
      add(:date_of_birth, :date, null: false)
      add(:country_code, :text, null: false)
      add(:kyc_status, :text, null: false, default: "unverified")
      add(:risk_level, :text, null: false, default: "low")
      add(:status, :text, null: false, default: "active")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)
      add(:state, :text, null: false, default: "active")
    end

    create(unique_index(:players, [:email], name: "players_unique_email_index"))

    create(unique_index(:players, [:username], name: "players_unique_username_index"))

    create table(:pii_vaults, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(
        :player_id,
        references(:players,
          column: :id,
          name: "pii_vaults_player_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(:pii_type, :text, null: false)
      add(:encrypted_value, :text, null: false)
      add(:hash_digest, :text, null: false)
      add(:last_accessed_at, :utc_datetime)
      add(:access_count, :bigint, null: false, default: 0)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)
    end

    create table(:ledger_entries, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(
        :wallet_id,
        references(:wallets,
          column: :id,
          name: "ledger_entries_wallet_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(:amount, :money_with_currency, null: false)
      add(:direction, :text, null: false)
      add(:kind, :text, null: false)
      add(:idempotency_key, :text, null: false)
      add(:reference_id, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)
    end

    create(
      unique_index(:ledger_entries, [:idempotency_key],
        name: "ledger_entries_unique_idempotency_key_index"
      )
    )

    create table(:kyc_upload_tokens, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(
        :player_id,
        references(:players,
          column: :id,
          name: "kyc_upload_tokens_player_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(:token, :text, null: false)
      add(:expires_at, :utc_datetime, null: false)
      add(:consumed_at, :utc_datetime)
      add(:consumed_by_document_id, :uuid)

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)
    end

    create table(:kyc_documents, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(
        :player_id,
        references(:players,
          column: :id,
          name: "kyc_documents_player_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(:upload_token_id, :uuid, null: false)
      add(:document_type, :text, null: false)
      add(:storage_path, :text, null: false)
      add(:status, :text, null: false, default: "pending")
      add(:rejection_reason, :text)
      add(:verified_at, :utc_datetime)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)
    end

    create table(:games, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:provider_id, :uuid, null: false)
      add(:provider_game_code, :text, null: false)
      add(:title, :text, null: false)
      add(:category, :text, null: false)
      add(:rtp, :decimal, null: false)
      add(:volatility, :text, null: false)

      add(:synced_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)
    end

    create table(:game_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:game_id, :uuid, null: false)
      add(:version_code, :text, null: false)
      add(:status, :text, null: false, default: "active")
      add(:release_date, :date, null: false)
      add(:rtp_certified, :boolean, null: false, default: false)

      add(:synced_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)
    end

    create table(:game_catalogs, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:game_id, :uuid, null: false)
      add(:current_version_id, :uuid, null: false)
      add(:available_regions, :text)
      add(:published_at, :utc_datetime, null: false)
      add(:hidden, :boolean, null: false, default: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)
    end

    create table(:bonus_triggers, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:campaign_id, :uuid, null: false)
      add(:kind, :text, null: false)
      add(:enabled, :boolean, null: false, default: true)
      add(:params, :map, null: false, default: %{})
      add(:position, :bigint, null: false, default: 0)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:bonus_grants, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(
        :player_id,
        references(:players,
          column: :id,
          name: "bonus_grants_player_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(:campaign_id, :uuid, null: false)
      add(:amount, :money_with_currency, null: false)
      add(:wagering_remaining, :decimal, null: false)
      add(:status, :text, null: false, default: "active")
      add(:granted_at, :utc_datetime, null: false)
      add(:expires_at, :utc_datetime, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:state, :text, null: false, default: "active")
    end

    create table(:bonus_executions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:campaign_id, :uuid, null: false)
      add(:kind, :text, null: false)
      add(:params, :map, null: false, default: %{})
      add(:position, :bigint, null: false, default: 0)
      add(:enabled, :boolean, null: false, default: true)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:bonus_events, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:kind, :text, null: false)
      add(:player_id, :uuid, null: false)
      add(:wallet_id, :uuid)
      add(:amount, :money_with_currency)
      add(:currency, :text)
      add(:idempotency_key, :text, null: false)
      add(:payload, :map, null: false, default: %{})
      add(:processed_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)
    end

    create(
      unique_index(:bonus_events, [:idempotency_key],
        name: "bonus_events_unique_idempotency_key_index"
      )
    )

    create table(:bonus_conditions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:group_id, :uuid, null: false)
      add(:kind, :text, null: false)
      add(:params, :map, null: false, default: %{})
      add(:negated, :boolean, null: false, default: false)
      add(:position, :bigint, null: false, default: 0)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:bonus_condition_groups, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:bonus_conditions) do
      modify(
        :group_id,
        references(:bonus_condition_groups,
          column: :id,
          name: "bonus_conditions_group_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:bonus_condition_groups) do
      add(:campaign_id, :uuid, null: false)
      add(:parent_group_id, :uuid)
      add(:combinator, :text, null: false, default: "all")
      add(:position, :bigint, null: false, default: 0)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:bonus_campaigns, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:bonus_triggers) do
      modify(
        :campaign_id,
        references(:bonus_campaigns,
          column: :id,
          name: "bonus_triggers_campaign_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:bonus_grants) do
      modify(
        :campaign_id,
        references(:bonus_campaigns,
          column: :id,
          name: "bonus_grants_campaign_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:bonus_executions) do
      modify(
        :campaign_id,
        references(:bonus_campaigns,
          column: :id,
          name: "bonus_executions_campaign_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:bonus_condition_groups) do
      modify(
        :campaign_id,
        references(:bonus_campaigns,
          column: :id,
          name: "bonus_condition_groups_campaign_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :parent_group_id,
        references(:bonus_condition_groups,
          column: :id,
          name: "bonus_condition_groups_parent_group_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:bonus_campaigns) do
      add(:name, :text, null: false)
      add(:kind, :text, null: false)
      add(:status, :text, null: false, default: "draft")
      add(:eligibility_rule, :text, null: false)
      add(:bonus_amount, :money_with_currency, null: false)
      add(:wagering_multiplier, :decimal, null: false)
      add(:max_redemptions, :bigint)
      add(:starts_at, :utc_datetime, null: false)
      add(:expires_at, :utc_datetime, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:state, :text, null: false, default: "draft")
    end

    create table(:audit_entries, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:actor_id, :uuid)
      add(:actor_type, :text, null: false)
      add(:action, :text, null: false)
      add(:resource_type, :text, null: false)
      add(:resource_id, :uuid, null: false)
      add(:changes, :map)
      add(:reason, :text)

      add(:recorded_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)
    end
  end

  def down do
    drop(table(:audit_entries))

    alter table(:bonus_campaigns) do
      remove(:state)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:expires_at)
      remove(:starts_at)
      remove(:max_redemptions)
      remove(:wagering_multiplier)
      remove(:bonus_amount)
      remove(:eligibility_rule)
      remove(:status)
      remove(:kind)
      remove(:name)
    end

    drop(constraint(:bonus_condition_groups, "bonus_condition_groups_campaign_id_fkey"))

    drop(constraint(:bonus_condition_groups, "bonus_condition_groups_parent_group_id_fkey"))

    alter table(:bonus_condition_groups) do
      modify(:parent_group_id, :uuid)
      modify(:campaign_id, :uuid)
    end

    drop(constraint(:bonus_executions, "bonus_executions_campaign_id_fkey"))

    alter table(:bonus_executions) do
      modify(:campaign_id, :uuid)
    end

    drop(constraint(:bonus_grants, "bonus_grants_campaign_id_fkey"))

    alter table(:bonus_grants) do
      modify(:campaign_id, :uuid)
    end

    drop(constraint(:bonus_triggers, "bonus_triggers_campaign_id_fkey"))

    alter table(:bonus_triggers) do
      modify(:campaign_id, :uuid)
    end

    drop(table(:bonus_campaigns))

    alter table(:bonus_condition_groups) do
      remove(:updated_at)
      remove(:inserted_at)
      remove(:position)
      remove(:combinator)
      remove(:parent_group_id)
      remove(:campaign_id)
    end

    drop(constraint(:bonus_conditions, "bonus_conditions_group_id_fkey"))

    alter table(:bonus_conditions) do
      modify(:group_id, :uuid)
    end

    drop(table(:bonus_condition_groups))

    drop(table(:bonus_conditions))

    drop_if_exists(
      unique_index(:bonus_events, [:idempotency_key],
        name: "bonus_events_unique_idempotency_key_index"
      )
    )

    drop(table(:bonus_events))

    drop(table(:bonus_executions))

    drop(constraint(:bonus_grants, "bonus_grants_player_id_fkey"))

    drop(table(:bonus_grants))

    drop(table(:bonus_triggers))

    drop(table(:game_catalogs))

    drop(table(:game_versions))

    drop(table(:games))

    drop(constraint(:kyc_documents, "kyc_documents_player_id_fkey"))

    drop(table(:kyc_documents))

    drop(constraint(:kyc_upload_tokens, "kyc_upload_tokens_player_id_fkey"))

    drop(table(:kyc_upload_tokens))

    drop(constraint(:ledger_entries, "ledger_entries_wallet_id_fkey"))

    drop_if_exists(
      unique_index(:ledger_entries, [:idempotency_key],
        name: "ledger_entries_unique_idempotency_key_index"
      )
    )

    drop(table(:ledger_entries))

    drop(constraint(:pii_vaults, "pii_vaults_player_id_fkey"))

    drop(table(:pii_vaults))

    drop_if_exists(unique_index(:players, [:username], name: "players_unique_username_index"))

    drop_if_exists(unique_index(:players, [:email], name: "players_unique_email_index"))

    alter table(:players) do
      remove(:state)
      remove(:archived_at)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:status)
      remove(:risk_level)
      remove(:kyc_status)
      remove(:country_code)
      remove(:date_of_birth)
      remove(:username)
      remove(:email)
    end

    drop(constraint(:self_exclusion_records, "self_exclusion_records_player_id_fkey"))

    alter table(:self_exclusion_records) do
      modify(:player_id, :uuid)
    end

    drop(constraint(:wallets, "wallets_player_id_fkey"))

    alter table(:wallets) do
      modify(:player_id, :uuid)
    end

    drop(constraint(:withdrawal_requests, "withdrawal_requests_player_id_fkey"))

    drop(constraint(:withdrawal_requests, "withdrawal_requests_wallet_id_fkey"))

    alter table(:withdrawal_requests) do
      modify(:wallet_id, :uuid)
      modify(:player_id, :uuid)
    end

    drop(table(:players))

    drop(table(:provider_configs))

    drop(table(:self_exclusion_records))

    alter table(:tokens) do
      remove(:archived_at)
    end

    drop(constraint(:tokens_versions, "tokens_versions_version_source_id_fkey"))

    alter table(:tokens_versions) do
      modify(:version_source_id, :text)
    end

    drop(table(:tokens))

    drop(table(:tokens_versions))

    drop(table(:transfers))

    drop_if_exists(unique_index(:users, [:email], name: "users_unique_email_index"))

    alter table(:users) do
      remove(:archived_at)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:hashed_password)
      remove(:email)
    end

    drop(constraint(:users_versions, "users_versions_version_source_id_fkey"))

    alter table(:users_versions) do
      modify(:version_source_id, :uuid)
    end

    drop(table(:users))

    drop(table(:users_versions))

    drop(table(:wallets))

    drop(table(:withdrawal_requests))

    drop_if_exists(
      unique_index(:withdrawal_webhook_events, [:provider, :provider_reference, :event_type],
        name: "withdrawal_webhook_events_unique_provider_reference_event_index"
      )
    )

    drop(table(:withdrawal_webhook_events))
  end
end
